const mongoose = require('mongoose');
const College  = require('./models/College');
require('dotenv').config();

const MONGO_URI =
  process.env.MONGO_URI || 'mongodb://localhost:27017/college_platform';

const colleges = [
  {
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    location: { city: 'Mumbai', state: 'Maharashtra' },
    type: 'Government',
    established: 1958,
    description:
      'IIT Bombay is one of the foremost institutes of national importance. Considered the second oldest IIT, it excels in technology, research, and management education.',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    fees: { min: 200000, max: 400000 },
    rating: 4.9,
    courseTags: ['Engineering', 'Technology', 'Science', 'Management', 'Design'],
    courses: [
      { name: 'B.Tech Computer Science',       duration: '4 years', fees: 250000, seats: 120 },
      { name: 'B.Tech Electrical Engineering', duration: '4 years', fees: 250000, seats: 90  },
      { name: 'M.Tech',                        duration: '2 years', fees: 120000, seats: 200 },
      { name: 'MBA',                           duration: '2 years', fees: 400000, seats: 60  },
      { name: 'Ph.D',                          duration: '4-6 years', fees: 50000, seats: 500 },
    ],
    placement: {
      averagePackage: 2200000,
      highestPackage: 25000000,
      placementRate:  98,
      topRecruiters:  ['Google', 'Microsoft', 'Goldman Sachs', 'McKinsey', 'Amazon'],
    },
    rankings:     { nirf: 3, qs: 149, outlook: 2 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Healthcare', 'Cafeteria', 'Swimming Pool'],
    examAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    reviews: [
      { author: 'Rahul M',  rating: 5, comment: 'World class faculty and amazing research opportunities.', date: new Date('2024-01-15') },
      { author: 'Priya K',  rating: 5, comment: 'Best decision of my life. Placements are exceptional.',  date: new Date('2024-02-10') },
      { author: 'Arjun S',  rating: 4, comment: 'Academically rigorous but very rewarding.',              date: new Date('2024-03-05') },
    ],
    totalReviews: 3,
  },
  {
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    location: { city: 'New Delhi', state: 'Delhi' },
    type: 'Government',
    established: 1961,
    description:
      'IIT Delhi is one of the premier engineering institutions in India, located in the capital. It has produced top engineers, scientists and entrepreneurs.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    fees: { min: 200000, max: 380000 },
    rating: 4.8,
    courseTags: ['Engineering', 'Technology', 'Science', 'Management'],
    courses: [
      { name: 'B.Tech Computer Science',       duration: '4 years', fees: 230000, seats: 100 },
      { name: 'B.Tech Mechanical Engineering', duration: '4 years', fees: 230000, seats: 80  },
      { name: 'M.Tech',                        duration: '2 years', fees: 100000, seats: 250 },
      { name: 'MBA',                           duration: '2 years', fees: 380000, seats: 50  },
    ],
    placement: {
      averagePackage: 2000000,
      highestPackage: 22000000,
      placementRate:  97,
      topRecruiters:  ['Microsoft', 'Google', 'Apple', 'Flipkart', 'Uber'],
    },
    rankings:     { nirf: 2, qs: 185, outlook: 1 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Healthcare', 'Innovation Hub'],
    examAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    reviews: [
      { author: 'Vikram T', rating: 5, comment: 'Incredible infrastructure and proximity to top MNCs.', date: new Date('2024-01-20') },
      { author: 'Sneha R',  rating: 4, comment: 'Highly competitive environment. Faculty is exceptional.', date: new Date('2024-02-15') },
    ],
    totalReviews: 2,
  },
  {
    name: 'Indian Institute of Management Ahmedabad',
    slug: 'iim-ahmedabad',
    location: { city: 'Ahmedabad', state: 'Gujarat' },
    type: 'Government',
    established: 1961,
    description:
      'IIM Ahmedabad is considered the best business school in Asia. Consistently ranked as the top management institution in India.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    fees: { min: 2300000, max: 2500000 },
    rating: 4.9,
    courseTags: ['Management', 'MBA', 'Finance', 'Marketing', 'Entrepreneurship'],
    courses: [
      { name: 'PGP (MBA)',                  duration: '2 years', fees: 2500000, seats: 395 },
      { name: 'PGPX (Executive MBA)',       duration: '1 year',  fees: 3200000, seats: 80  },
      { name: 'Ph.D',                       duration: '5 years', fees: 100000,  seats: 30  },
    ],
    placement: {
      averagePackage: 3500000,
      highestPackage: 10000000,
      placementRate:  100,
      topRecruiters:  ['McKinsey', 'BCG', 'Bain', 'Goldman Sachs', 'Amazon'],
    },
    rankings:     { nirf: 1, qs: 44, outlook: 1 },
    facilities:   ['Library', 'Case Study Rooms', 'Sports Complex', 'Hostel', 'Healthcare', 'Entrepreneurship Center'],
    examAccepted: ['CAT', 'GMAT'],
    reviews: [
      { author: 'Aditya P', rating: 5, comment: 'Transformative 2 years. Case study method is unparalleled.', date: new Date('2024-01-10') },
      { author: 'Meera G',  rating: 5, comment: 'Best MBA in India, period. Alumni network opens every door.', date: new Date('2024-02-20') },
    ],
    totalReviews: 2,
  },
  {
    name: 'BITS Pilani',
    slug: 'bits-pilani',
    location: { city: 'Pilani', state: 'Rajasthan' },
    type: 'Deemed',
    established: 1964,
    description:
      'Birla Institute of Technology & Science is among India\'s most prestigious private institutions. Famous for its Practice School program.',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    fees: { min: 500000, max: 700000 },
    rating: 4.6,
    courseTags: ['Engineering', 'Science', 'Technology', 'Pharmacy'],
    courses: [
      { name: 'B.E. Computer Science', duration: '4 years', fees: 620000, seats: 200 },
      { name: 'B.E. Electronics',      duration: '4 years', fees: 600000, seats: 150 },
      { name: 'B.Pharm',               duration: '4 years', fees: 550000, seats: 80  },
      { name: 'M.E.',                  duration: '2 years', fees: 450000, seats: 100 },
    ],
    placement: {
      averagePackage: 1800000,
      highestPackage: 15000000,
      placementRate:  95,
      topRecruiters:  ['Google', 'Microsoft', 'Qualcomm', 'Samsung', 'DE Shaw'],
    },
    rankings:     { nirf: 25, qs: 650, outlook: 12 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Auditorium', 'Food Court'],
    examAccepted: ['BITSAT'],
    reviews: [
      { author: 'Kartik L',  rating: 5, comment: 'Campus life is amazing. Practice School gives real industry exposure.', date: new Date('2024-01-25') },
      { author: 'Ananya B',  rating: 4, comment: 'Great college for engineering. The dual degree is unique.',           date: new Date('2024-03-01') },
    ],
    totalReviews: 2,
  },
  {
    name: 'Vellore Institute of Technology',
    slug: 'vit-vellore',
    location: { city: 'Vellore', state: 'Tamil Nadu' },
    type: 'Deemed',
    established: 1984,
    description:
      'VIT is one of India\'s largest and most reputed private universities, known for its industry connections and excellent placement record.',
    image: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&q=80',
    fees: { min: 350000, max: 550000 },
    rating: 4.2,
    courseTags: ['Engineering', 'Technology', 'Science', 'Management'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 490000, seats: 1500 },
      { name: 'B.Tech Mechanical',       duration: '4 years', fees: 460000, seats: 500  },
      { name: 'MBA',                     duration: '2 years', fees: 550000, seats: 300  },
      { name: 'M.Tech',                  duration: '2 years', fees: 250000, seats: 400  },
    ],
    placement: {
      averagePackage: 900000,
      highestPackage: 9000000,
      placementRate:  88,
      topRecruiters:  ['Wipro', 'TCS', 'Infosys', 'Cognizant', 'Accenture'],
    },
    rankings:     { nirf: 11, qs: 801, outlook: 8 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Healthcare', 'Shopping Center'],
    examAccepted: ['VITEEE', 'JEE Main'],
    reviews: [
      { author: 'Deepak N', rating: 4, comment: 'Excellent industry connections. Campus is huge.',         date: new Date('2024-02-05') },
      { author: 'Shreya M', rating: 4, comment: 'Good placement record. Faculty quality varies by dept.', date: new Date('2024-02-28') },
    ],
    totalReviews: 2,
  },
  {
    name: 'Manipal Institute of Technology',
    slug: 'manipal-institute-of-technology',
    location: { city: 'Manipal', state: 'Karnataka' },
    type: 'Private',
    established: 1957,
    description:
      'One of India\'s oldest respected private engineering institutions. MIT Manipal is known for its international exposure and excellent campus.',
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80',
    fees: { min: 400000, max: 600000 },
    rating: 4.3,
    courseTags: ['Engineering', 'Technology', 'Architecture', 'Science'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 560000, seats: 600 },
      { name: 'B.Tech Mechanical',       duration: '4 years', fees: 520000, seats: 300 },
      { name: 'B.Arch',                  duration: '5 years', fees: 480000, seats: 80  },
      { name: 'M.Tech',                  duration: '2 years', fees: 250000, seats: 200 },
    ],
    placement: {
      averagePackage: 1100000,
      highestPackage: 11000000,
      placementRate:  90,
      topRecruiters:  ['Infosys', 'Wipro', 'Mindtree', 'Amazon', 'Oracle'],
    },
    rankings:     { nirf: 48, qs: 1000, outlook: 22 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Healthcare', 'Innovation Center'],
    examAccepted: ['MU OET', 'JEE Main'],
    reviews: [
      { author: 'Rohan V', rating: 4, comment: 'Great campus life and decent placements.', date: new Date('2024-01-30') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    location: { city: 'New Delhi', state: 'Delhi' },
    type: 'Government',
    established: 1941,
    description:
      'Formerly Delhi College of Engineering, DTU is one of the oldest and most prestigious engineering colleges in India.',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    fees: { min: 150000, max: 200000 },
    rating: 4.2,
    courseTags: ['Engineering', 'Technology', 'Science'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 170000, seats: 200 },
      { name: 'B.Tech Electronics',      duration: '4 years', fees: 160000, seats: 180 },
      { name: 'M.Tech',                  duration: '2 years', fees: 80000,  seats: 150 },
    ],
    placement: {
      averagePackage: 1400000,
      highestPackage: 12000000,
      placementRate:  92,
      topRecruiters:  ['Samsung', 'Adobe', 'Amazon', 'Paytm', 'Zomato'],
    },
    rankings:     { nirf: 36, qs: 1200, outlook: 18 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Canteen'],
    examAccepted: ['JEE Main'],
    reviews: [
      { author: 'Divya P', rating: 4, comment: 'Excellent value for money. Government fees, great placements.', date: new Date('2024-02-15') },
      { author: 'Amit K',  rating: 4, comment: 'Strong alumni network in Delhi NCR.',                           date: new Date('2024-03-10') },
    ],
    totalReviews: 2,
  },
  {
    name: 'National Institute of Technology Trichy',
    slug: 'nit-trichy',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
    type: 'Government',
    established: 1964,
    description:
      'NIT Trichy is consistently ranked among the top NITs in India, known for its excellent academic culture and placement record.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    fees: { min: 130000, max: 200000 },
    rating: 4.5,
    courseTags: ['Engineering', 'Technology', 'Architecture', 'Science'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 150000, seats: 120 },
      { name: 'B.Tech Mechanical',       duration: '4 years', fees: 140000, seats: 100 },
      { name: 'B.Arch',                  duration: '5 years', fees: 130000, seats: 40  },
      { name: 'M.Tech',                  duration: '2 years', fees: 80000,  seats: 200 },
    ],
    placement: {
      averagePackage: 1600000,
      highestPackage: 18000000,
      placementRate:  96,
      topRecruiters:  ['Microsoft', 'Amazon', 'Qualcomm', 'Intel', 'Samsung'],
    },
    rankings:     { nirf: 9, qs: 1000, outlook: 5 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Healthcare'],
    examAccepted: ['JEE Main'],
    reviews: [
      { author: 'Karthik R', rating: 5, comment: 'One of the best NITs! Great faculty and placement opportunities.', date: new Date('2024-01-15') },
    ],
    totalReviews: 1,
  },
  {
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-ist',
    location: { city: 'Chennai', state: 'Tamil Nadu' },
    type: 'Deemed',
    established: 1985,
    description:
      'SRM is one of the top-ranking universities in India with diverse academic programs and strong industry partnerships.',
    image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80',
    fees: { min: 250000, max: 450000 },
    rating: 3.9,
    courseTags: ['Engineering', 'Medical', 'Management', 'Science', 'Arts'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 350000,  seats: 2000 },
      { name: 'MBBS',                    duration: '5.5 years', fees: 1200000, seats: 150  },
      { name: 'MBA',                     duration: '2 years', fees: 450000,  seats: 400  },
    ],
    placement: {
      averagePackage: 700000,
      highestPackage: 8000000,
      placementRate:  82,
      topRecruiters:  ['TCS', 'Wipro', 'CTS', 'Capgemini', 'IBM'],
    },
    rankings:     { nirf: 38, qs: 1201, outlook: 25 },
    facilities:   ['Library', 'Hospital', 'Sports Complex', 'Hostel', 'Labs'],
    examAccepted: ['SRMJEEE', 'JEE Main'],
    reviews: [
      { author: 'Pooja V', rating: 4, comment: 'Large campus with many facilities. Good for networking.', date: new Date('2024-02-22') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Amity University',
    slug: 'amity-university-noida',
    location: { city: 'Noida', state: 'Uttar Pradesh' },
    type: 'Private',
    established: 1995,
    description:
      'Amity is one of India\'s largest private universities offering a wide range of programs with modern campus infrastructure.',
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
    fees: { min: 300000, max: 600000 },
    rating: 3.7,
    courseTags: ['Engineering', 'Management', 'Law', 'Journalism', 'Arts', 'Science'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 500000, seats: 800 },
      { name: 'MBA',                     duration: '2 years', fees: 600000, seats: 500 },
      { name: 'B.Com (Hons)',            duration: '3 years', fees: 300000, seats: 600 },
      { name: 'LLB',                     duration: '3 years', fees: 350000, seats: 200 },
    ],
    placement: {
      averagePackage: 600000,
      highestPackage: 5000000,
      placementRate:  75,
      topRecruiters:  ['Deloitte', 'EY', 'KPMG', 'TCS', 'HCL'],
    },
    rankings:     { nirf: 78, outlook: 42 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Healthcare', 'Gym'],
    examAccepted: ['Amity JEE', 'JEE Main', 'CAT', 'GMAT', 'SAT'],
    reviews: [
      { author: 'Naman S', rating: 3, comment: 'Good campus and facilities. Placement could be better for non-IT.', date: new Date('2024-03-05') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    location: { city: 'Kolkata', state: 'West Bengal' },
    type: 'Government',
    established: 1955,
    description:
      'Jadavpur University is one of the most prestigious universities in India, known for its strong engineering and arts programs.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    fees: { min: 50000, max: 150000 },
    rating: 4.4,
    courseTags: ['Engineering', 'Arts', 'Science', 'Technology'],
    courses: [
      { name: 'B.E. Computer Science', duration: '4 years', fees: 80000, seats: 120 },
      { name: 'B.E. Electrical',       duration: '4 years', fees: 75000, seats: 80  },
      { name: 'M.E.',                  duration: '2 years', fees: 50000, seats: 100 },
      { name: 'B.A.',                  duration: '3 years', fees: 40000, seats: 300 },
    ],
    placement: {
      averagePackage: 1200000,
      highestPackage: 13000000,
      placementRate:  89,
      topRecruiters:  ['TCS', 'Infosys', 'Cognizant', 'IBM', 'Wipro'],
    },
    rankings:     { nirf: 14, qs: 801, outlook: 9 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Healthcare'],
    examAccepted: ['WBJEE'],
    reviews: [
      { author: 'Sumedha B', rating: 4, comment: 'Exceptional value. Great faculty at incredibly low fees.', date: new Date('2024-01-22') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Symbiosis Institute of Business Management',
    slug: 'sibm-pune',
    location: { city: 'Pune', state: 'Maharashtra' },
    type: 'Deemed',
    established: 1978,
    description:
      'SIBM Pune is one of India\'s premier management institutes offering world-class MBA programs with strong industry linkages.',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    fees: { min: 1800000, max: 2000000 },
    rating: 4.3,
    courseTags: ['Management', 'MBA', 'Finance', 'Marketing', 'HR'],
    courses: [
      { name: 'MBA',                                  duration: '2 years', fees: 1950000, seats: 240 },
      { name: 'MBA (Innovation & Entrepreneurship)',  duration: '2 years', fees: 2000000, seats: 60  },
    ],
    placement: {
      averagePackage: 2200000,
      highestPackage: 8000000,
      placementRate:  100,
      topRecruiters:  ['HDFC Bank', 'Wipro', 'Deloitte', 'Amazon', 'Goldman Sachs'],
    },
    rankings:     { nirf: 22, outlook: 8 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Business Incubator'],
    examAccepted: ['SNAP', 'CAT', 'GMAT'],
    reviews: [
      { author: 'Riya P', rating: 4, comment: 'Excellent MBA program. Great campus and strong corporate connections.', date: new Date('2024-02-18') },
    ],
    totalReviews: 1,
  },
  {
    name: 'IIT Roorkee',
    slug: 'iit-roorkee',
    location: { city: 'Roorkee', state: 'Uttarakhand' },
    type: 'Government',
    established: 1847,
    description:
      'The oldest technical institution in Asia. IIT Roorkee has a glorious history and consistently ranks among the top IITs for research and placements.',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    fees: { min: 200000, max: 350000 },
    rating: 4.7,
    courseTags: ['Engineering', 'Technology', 'Architecture', 'Science', 'Management'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 250000, seats: 90 },
      { name: 'B.Arch',                  duration: '5 years', fees: 220000, seats: 40 },
      { name: 'M.Tech',                  duration: '2 years', fees: 100000, seats: 300 },
      { name: 'MBA',                     duration: '2 years', fees: 350000, seats: 55 },
    ],
    placement: {
      averagePackage: 1900000,
      highestPackage: 20000000,
      placementRate:  97,
      topRecruiters:  ['Google', 'Adobe', 'Microsoft', 'Goldman Sachs', 'Apple'],
    },
    rankings:     { nirf: 6, qs: 369, outlook: 4 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Hospital', 'Swimming Pool'],
    examAccepted: ['JEE Advanced', 'GATE', 'CAT'],
    reviews: [
      { author: 'Siddharth M', rating: 5, comment: 'Oldest IIT. Beautiful heritage campus and excellent academics.', date: new Date('2024-01-05') },
    ],
    totalReviews: 1,
  },
  {
    name: 'XLRI Jamshedpur',
    slug: 'xlri-jamshedpur',
    location: { city: 'Jamshedpur', state: 'Jharkhand' },
    type: 'Autonomous',
    established: 1949,
    description:
      'XLRI is one of India\'s premier HR management and business institutions, known for its humanistic approach to management education.',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    fees: { min: 2300000, max: 2500000 },
    rating: 4.7,
    courseTags: ['Management', 'MBA', 'HR', 'Finance', 'Marketing'],
    courses: [
      { name: 'PGDM (BM)',  duration: '2 years', fees: 2450000, seats: 240 },
      { name: 'PGDM (HRM)', duration: '2 years', fees: 2300000, seats: 180 },
    ],
    placement: {
      averagePackage: 3000000,
      highestPackage: 9000000,
      placementRate:  100,
      topRecruiters:  ['McKinsey', 'Deloitte', 'HDFC Bank', 'Goldman Sachs', 'EY'],
    },
    rankings:     { nirf: 5, outlook: 3 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Chapel', 'Incubation Hub'],
    examAccepted: ['XAT', 'GMAT'],
    reviews: [
      { author: 'Pallavi D', rating: 5, comment: 'Premier HR school. Ethical business principles and strong alumni.', date: new Date('2024-01-12') },
    ],
    totalReviews: 1,
  },
  {
    name: 'NMIMS University',
    slug: 'nmims-university-mumbai',
    location: { city: 'Mumbai', state: 'Maharashtra' },
    type: 'Deemed',
    established: 1981,
    description:
      'NMIMS is a leading business and management university in Mumbai with strong industry connections in India\'s financial capital.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    fees: { min: 1600000, max: 2200000 },
    rating: 4.2,
    courseTags: ['Management', 'MBA', 'Finance', 'Pharmacy', 'Engineering', 'Law'],
    courses: [
      { name: 'MBA',     duration: '2 years', fees: 2200000, seats: 480 },
      { name: 'B.Pharm', duration: '4 years', fees: 400000,  seats: 120 },
      { name: 'B.Tech',  duration: '4 years', fees: 600000,  seats: 300 },
    ],
    placement: {
      averagePackage: 2000000,
      highestPackage: 7000000,
      placementRate:  99,
      topRecruiters:  ['JP Morgan', 'Accenture', 'Deloitte', 'Amazon', 'HDFC Bank'],
    },
    rankings:     { nirf: 28, outlook: 14 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Innovation Hub'],
    examAccepted: ['NMAT', 'CAT', 'GMAT'],
    reviews: [
      { author: 'Sonal D', rating: 4, comment: 'Prime location in Mumbai. Great for finance and marketing.', date: new Date('2024-02-22') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Chandigarh University',
    slug: 'chandigarh-university',
    location: { city: 'Mohali', state: 'Punjab' },
    type: 'Private',
    established: 2012,
    description:
      'Chandigarh University has emerged as one of the fastest-growing universities in India with diverse programs and placement success.',
    image: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80',
    fees: { min: 180000, max: 400000 },
    rating: 3.8,
    courseTags: ['Engineering', 'Management', 'Science', 'Arts', 'Hotel Management'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 320000, seats: 2000 },
      { name: 'MBA',                     duration: '2 years', fees: 400000, seats: 600  },
      { name: 'BBA',                     duration: '3 years', fees: 200000, seats: 800  },
    ],
    placement: {
      averagePackage: 700000,
      highestPackage: 5000000,
      placementRate:  78,
      topRecruiters:  ['TCS', 'Infosys', 'Amazon', 'Capgemini', 'IBM'],
    },
    rankings:     { nirf: 30, outlook: 28 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Startup Incubator'],
    examAccepted: ['CUCET', 'JEE Main', 'CAT'],
    reviews: [
      { author: 'Harleen K', rating: 4, comment: 'Modern campus with good placements. The tech fest is huge!', date: new Date('2024-02-08') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Thapar Institute of Engineering',
    slug: 'thapar-institute',
    location: { city: 'Patiala', state: 'Punjab' },
    type: 'Deemed',
    established: 1956,
    description:
      'Thapar Institute is a leading private engineering university known for its research output and placement record in North India.',
    image: 'https://images.unsplash.com/photo-1483653085484-eb63c9f02547?w=800&q=80',
    fees: { min: 450000, max: 650000 },
    rating: 4.2,
    courseTags: ['Engineering', 'Technology', 'Science'],
    courses: [
      { name: 'B.E. Computer Science', duration: '4 years', fees: 600000, seats: 200 },
      { name: 'B.E. Electrical',       duration: '4 years', fees: 580000, seats: 120 },
      { name: 'M.E.',                  duration: '2 years', fees: 250000, seats: 100 },
    ],
    placement: {
      averagePackage: 1500000,
      highestPackage: 10000000,
      placementRate:  93,
      topRecruiters:  ['Microsoft', 'Amazon', 'Samsung', 'Adobe', 'Wipro'],
    },
    rankings:     { nirf: 34, outlook: 16 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Innovation Center'],
    examAccepted: ['JEE Main', 'Thapar Entrance'],
    reviews: [
      { author: 'Gurpreet S', rating: 4, comment: 'Great placement record for a private college. Strong CS dept.', date: new Date('2024-01-28') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Lovely Professional University',
    slug: 'lovely-professional-university',
    location: { city: 'Phagwara', state: 'Punjab' },
    type: 'Private',
    established: 2005,
    description:
      'LPU is India\'s largest single-campus university offering 200+ programs, known for its modern infrastructure and diverse student body.',
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
    fees: { min: 150000, max: 400000 },
    rating: 3.6,
    courseTags: ['Engineering', 'Management', 'Arts', 'Design', 'Hospitality', 'Science'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 280000, seats: 3000 },
      { name: 'MBA',                     duration: '2 years', fees: 400000, seats: 1000 },
      { name: 'B.Design',               duration: '4 years', fees: 300000, seats: 200  },
    ],
    placement: {
      averagePackage: 550000,
      highestPackage: 4500000,
      placementRate:  70,
      topRecruiters:  ['TCS', 'Wipro', 'Amazon', 'Capgemini', 'HCL'],
    },
    rankings:     { nirf: 58, outlook: 45 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Shopping Mall', 'Hospital', 'Cinema'],
    examAccepted: ['LPUNEST', 'JEE Main', 'CAT'],
    reviews: [
      { author: 'Abhishek T', rating: 3, comment: 'Massive campus with all facilities. Placement varies by branch.', date: new Date('2024-02-14') },
    ],
    totalReviews: 1,
  },
  {
    name: 'PES University',
    slug: 'pes-university-bangalore',
    location: { city: 'Bangalore', state: 'Karnataka' },
    type: 'Deemed',
    established: 1988,
    description:
      'PES University is a leading private university in Bangalore known for its strong engineering programs and Silicon Valley connections.',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    fees: { min: 280000, max: 480000 },
    rating: 4.0,
    courseTags: ['Engineering', 'Technology', 'Science', 'Management'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 450000, seats: 500 },
      { name: 'B.Tech AI & ML',          duration: '4 years', fees: 480000, seats: 120 },
      { name: 'M.Tech',                  duration: '2 years', fees: 200000, seats: 100 },
    ],
    placement: {
      averagePackage: 1200000,
      highestPackage: 10000000,
      placementRate:  90,
      topRecruiters:  ['Amazon', 'Flipkart', 'SAP', 'Philips', 'Bosch'],
    },
    rankings:     { nirf: 75, outlook: 38 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Startup Hub'],
    examAccepted: ['PESSAT', 'JEE Main'],
    reviews: [
      { author: 'Harsha M', rating: 4, comment: 'Best private college in Bangalore for CS. Great industry links.', date: new Date('2024-03-08') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Shiv Nadar University',
    slug: 'shiv-nadar-university',
    location: { city: 'Greater Noida', state: 'Uttar Pradesh' },
    type: 'Private',
    established: 2011,
    description:
      'A research-intensive multidisciplinary university founded by HCL\'s Shiv Nadar. Known for its liberal education approach.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    fees: { min: 350000, max: 550000 },
    rating: 4.1,
    courseTags: ['Engineering', 'Science', 'Management', 'Humanities', 'Arts'],
    courses: [
      { name: 'B.Tech Computer Science', duration: '4 years', fees: 500000, seats: 300 },
      { name: 'B.Sc Research',           duration: '4 years', fees: 400000, seats: 200 },
      { name: 'MBA',                     duration: '2 years', fees: 550000, seats: 80  },
    ],
    placement: {
      averagePackage: 1300000,
      highestPackage: 9000000,
      placementRate:  88,
      topRecruiters:  ['HCL', 'Amazon', 'Schlumberger', 'Samsung', 'Cisco'],
    },
    rankings:     { nirf: 47, outlook: 22 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Art Gallery'],
    examAccepted: ['JEE Main', 'JEE Advanced', 'SAT'],
    reviews: [
      { author: 'Ishaan C', rating: 4, comment: 'Liberal education approach is refreshing. Great undergrad research.', date: new Date('2024-01-18') },
    ],
    totalReviews: 1,
  },
  {
    name: 'Panjab University',
    slug: 'panjab-university-chandigarh',
    location: { city: 'Chandigarh', state: 'Punjab' },
    type: 'Government',
    established: 1882,
    description:
      'One of the oldest and most prestigious universities in North India, offering programs in arts, science, commerce and professional fields.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    fees: { min: 30000, max: 150000 },
    rating: 3.8,
    courseTags: ['Arts', 'Science', 'Commerce', 'Law', 'Engineering', 'Medical'],
    courses: [
      { name: 'B.Sc Computer Science', duration: '3 years', fees: 60000,  seats: 200 },
      { name: 'B.Com',                 duration: '3 years', fees: 30000,  seats: 500 },
      { name: 'LLB',                   duration: '3 years', fees: 80000,  seats: 200 },
      { name: 'MBA',                   duration: '2 years', fees: 150000, seats: 120 },
    ],
    placement: {
      averagePackage: 500000,
      highestPackage: 3000000,
      placementRate:  68,
      topRecruiters:  ['TCS', 'Punjab National Bank', 'Infosys', 'HCL', 'Wipro'],
    },
    rankings:     { nirf: 33, outlook: 30 },
    facilities:   ['Library', 'Sports Complex', 'Hostel', 'Labs', 'Cultural Center'],
    examAccepted: ['CET', 'CLAT', 'CAT'],
    reviews: [
      { author: 'Sukhpreet K', rating: 4, comment: 'Great value for money. Historic campus and good faculty.', date: new Date('2024-03-02') },
    ],
    totalReviews: 1,
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    await College.deleteMany({});
    console.log('🗑️  Cleared existing colleges');

    const inserted = await College.insertMany(colleges);
    console.log(`✅ Seeded ${inserted.length} colleges successfully`);

    await mongoose.disconnect();
    console.log('Disconnected.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
}

seed();